### PR TITLE
Adding mnemonics support

### PR DESCRIPTION
**Pull request by hczerpak**
I wrote some based on libra wallet code. I will need to have mnemonic support for a project of mine so I'm wondering if you guys would want something like this merged in? It is not finished, no tests and some duplications vs your code but first I want to know if you like it. So I know if I can work on it more or drop it.

Let me know what to change or redo if you have any criticism.

### CODE REVIEW

**Comment by ice09** [comment]
Looks good and makes sense to support Mnemonics, @ketola what do you think? To me, we could go with this version, there are no additional dependencies and it looks straightforward.  
Just not sure if reusing an existing solution might make sense here, like (randomly chosen) https://novacrypto.github.io/BIP39/
@hczerpak Did you look into existing Mnemonics support for Java?

**Comment by ketola** [comment]
Yes, this looks like cool feature to have. Thanks for the PR! 
I know the concept of mnemonics, but not the details very well so I need some time to go through this. Also from security point of view, it's very important to make sure this works correctly. 

@hczerpak, is this implementation based on some standard or other implementation I could use as reference? I will probably add some other questions in code too.

After that, we could pull this to a separate branch to work on some tests and examples before merging to master.

Also the possibility to utilize existing implementations should be researched as @ice09 pointed out.

**Comment by hczerpak** [comment]
This implementation is basically the code from https://github.com/libra/libra/tree/master/client/libra_wallet/src rewritten in java.
I don't think mnemonics from Libra implementation matches BIP39. It uses different hashes. For me it makes sense to match the implementation from Libra rather than from Bitcoin.
So if I create an account in libra-cli I'd like to be able to import it here.

**Comment by hczerpak** [comment]
I'll try to finish it over the weekend. Add some tests and remove not needed code in my fork.

**Comment by ketola** [comment]
@hczerpak, sounds good. Have you been able to verify that importing account from libra cli works?

**Comment by hczerpak** [comment]
There are sample mnemonics used in Libra tests I will write unit tests using those and it should be a good start. Is there a simple way to mark this PR as "draft" or wip?

**Comment by ice09** [comment]
@hczerpak do you think this can be merged to master right now? I am not sure about marking this as WIP, for me including it in master makes sense for now.
Unrelated, but maybe helpful: would you like to join out Telegram channel, as discussions might be faster here?  Link: https://t.me/joinchat/DAQb4RSNpqEok3p-QdmaKQ

**Pull request merged**
